[package]
name = "stage_1st"
version = "0.1.0"
authors = ["ellbrid <ell@exoskeleton.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plankton = { path = "../plankton" }
